spring.application.name=lojadelivrosapi
spring.profiles.active=dev
api.version=1.0.0

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
